quest_generation:
  description: >
    Generate daily quests and price prediction challenges based on current blockchain market data 
    and player history for date {current_date}.

    Process:
    1. Use `Search the internet with Serper` (tool) to search for trending blockchain/crypto news and market movements in the last 24 hours.
    2. Analyze player's historical performance, preferred tokens, and difficulty level.
    3. Generate 3-5 diverse quests including:
      - Price prediction challenges for major cryptocurrencies
      - Social engagement tasks (Twitter/Discord interactions)
      - Educational quizzes about blockchain technology
      - Trading simulation challenges
    4. Set appropriate difficulty levels and reward tiers based on player profile.

    Constraints:
    - Quests must be completable within 24 hours
    - Difficulty should match player's skill level (beginner/intermediate/advanced)
    - Rewards must align with the game's tokenomics
    - Include at least one social interaction quest

  expected_output: >
    A JSON structure containing:
    - Quest ID and type
    - Title and description in English
    - Completion criteria and time limits  
    - Reward structure (tokens, XP, NFTs)
    - Difficulty rating (1-10)

  agent: quest_agent

comprehensive_market_analysis:
  description: >
    Perform comprehensive market analysis combining news collection and market intelligence for {symbol} 
    as of {current_date}.

    Process:
    1. NEWS COLLECTION:
      - Find top 3 most impactful blockchain/crypto news from last 7 days
      - Focus on DeFi, GameFi, SocialFi developments affecting the ecosystem
      - Scrape detailed content from reputable sources (CoinDesk, Cointelegraph, The Block)
      - Analyze market impact and relevance to crypto gaming sector

    2. MARKET INTELLIGENCE:
      - On-chain metrics (active addresses, transaction volume, HODL patterns)
      - Exchange flows and whale wallet movements
      - Institutional adoption and corporate treasury updates
      - Regulatory developments and government policies
      - Macro economic factors (DXY, interest rates, inflation)
      - Network health, security metrics, and mining statistics

    Constraints:
    - Only articles published within the last 7 days
    - Prioritize news from reputable sources
    - Focus on developments impacting GameFi/SocialFi ecosystems
    - Use actual scraped data, no generated content

  expected_output: >
    Comprehensive market analysis report including:
    - Top 3 news articles with publication dates, sources, and market impact summaries
    - On-chain metrics analysis with trend identification and whale movement tracking
    - Regulatory and macro environment assessment with policy implications
    - Network health and security analysis with mining difficulty updates
    - Competitive landscape analysis and market positioning insights
    - Short/medium/long-term market outlook with confidence indicators

  agent: market_analyst

social_sentiment_analysis:
  description: >
    Analyze social media sentiment (Twitter, Reddit) for cryptocurrency {symbol} and 
    overall Web3/blockchain gaming market sentiment for {current_date}.

    Process:
    1. Use `Search the internet with Serper` to collect recent social media posts... and discussions about 
      the specified cryptocurrency and blockchain gaming trends.
    2. Analyze sentiment using natural language processing techniques.
    3. Identify key influencers, trending topics, and community concerns.
    4. Assess market psychology and potential price movement indicators.
    5. Generate insights relevant to SocialFi and GameFi sectors.

    Focus areas:
    - Overall market sentiment (bullish/bearish/neutral)
    - Community engagement levels
    - Influencer opinions and their potential impact
    - Emerging trends in blockchain gaming and SocialFi

  expected_output: >
    A comprehensive report in English (2-3 paragraphs) including:
    - Current sentiment score (1-10, where 10 is extremely bullish)
    - Key themes and discussions in the community
    - Influencer sentiment and notable opinions
    - Implications for players and investment strategies
    - Trending hashtags and social metrics

  agent: social_agent

technical_prediction_analysis:
  description: >
    Perform combined technical analysis and AI-powered price predictions for {symbol} on {current_date}.

    Process:
    1. TECHNICAL ANALYSIS:
      - Multi-timeframe analysis (1h, 4h, 1d, 1w) with trend identification
      - All major technical indicators (RSI, MACD, Bollinger Bands) with confluence analysis
      - Chart pattern recognition and Elliott Wave analysis
      - Volume profile and market structure analysis
      - Support/resistance levels with probability scoring
      - Fibonacci retracements and extensions

    2. AI PRICE PREDICTION:
      - LSTM neural network models trained on historical data
      - Multiple timeframe predictions (1d, 7d, 30d) with confidence intervals
      - Probability distributions and risk assessment
      - Market cycle analysis and positioning
      - Volatility forecasting and correlation analysis

    3. Generate specific entry prices, stop-loss levels, and profit targets with risk/reward ratios

  expected_output: >
    Technical prediction analysis report containing:
    - Multi-timeframe trend analysis with confluence scores
    - AI price predictions for 1d, 7d, 30d with confidence intervals and probability ranges
    - Specific trading signals with entry/exit levels and risk/reward ratios
    - Chart pattern analysis with price targets and breakout probabilities
    - Market structure analysis with institutional levels and key zones
    - Volatility forecasts and correlation analysis with major market factors

  agent: technical_prediction_engine

strategy_recommendation:
  description: >
    Generate comprehensive unified strategies combining trading, gaming optimization, and risk management 
    for {symbol} on {current_date}.

    Process:
    1. MARKET STRATEGY:
      - Entry/exit recommendations based on technical analysis and AI predictions
      - Position sizing using Kelly Criterion and risk parity methods
      - Portfolio allocation optimization for crypto gaming assets

    2. GAMING STRATEGY:
      - Prediction accuracy optimization using AI insights and market cycles
      - Social engagement strategies for maximum viral potential and community building
      - Quest completion optimization based on risk/reward ratios and time efficiency
      - Token staking strategies aligned with market cycles and yield opportunities
      - NFT acquisition timing based on market conditions and rarity analysis

    3. RISK MANAGEMENT:
      - Value at Risk (VaR) calculations for different confidence levels
      - Maximum Drawdown analysis and recovery time estimates
      - Portfolio optimization for GameFi/SocialFi ecosystem risks
      - Dynamic hedging strategies for volatile crypto markets

    4. SOCIAL STRATEGY:
      - Content creation templates for maximum engagement and viral potential
      - Community interaction timing and platform optimization
      - Influencer collaboration strategies and social momentum building

  expected_output: >
    Unified strategy report including:
    - Market trading strategy with specific entry/exit points, stop-losses, and profit targets
    - Gaming optimization tactics with quest prioritization and reward maximization
    - Risk management framework with VaR calculations and position sizing recommendations
    - Social engagement strategies with content templates and community building tactics
    - Portfolio allocation advice with asset diversification and yield optimization
    - Short/medium/long-term outlook with confidence scores and scenario planning

  agent: strategy_agent

community_support_and_rewards:
  description: >
    Manage community support and NFT rewards distribution for {current_date}.

    Process:
    1. NFT REWARD MANAGEMENT:
      - Monitor player achievements and milestone completions
      - Verify eligibility criteria for NFT rewards based on quest performance
      - Generate unique NFT metadata based on achievement type and rarity
      - Initiate minting process through smart contract integration
      - Distribute NFTs to eligible player wallets with confirmation tracking

    2. COMMUNITY SUPPORT:
      - Generate intelligent responses for player questions about strategy, gameplay, and features
      - Provide actionable advice with specific examples and current market context
      - Suggest related features, quests, and opportunities for player engagement
      - Maintain encouraging, gamified tone while ensuring user safety and responsible investing

    Handle user query: {user_question}

    Response guidelines:
    - Use natural, friendly language suitable for crypto gaming community
    - Provide practical, actionable advice with specific examples
    - Include relevant market data and strategy context when available
    - Encourage social interaction and community engagement
    - Always prioritize user safety and responsible investing practices

  expected_output: >
    Community support response including:
    - Direct answer to user question with practical, actionable advice
    - NFT reward eligibility status and distribution confirmations
    - Related features, quests, and opportunities for continued engagement
    - Market context and strategy insights relevant to the user's question
    - Encouraging guidance with appropriate financial disclaimers and safety reminders

  agent: community_support_manager
